# Generated by Django 2.1.3 on 2018-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('dept_name', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
